Fix problems when sys.executable is slightly different to argv[0]
pypa/setuptools pull request #2697
Opened 2021-06-16 19:15 UTC by set-soft

## Summary of changes

This patch fixes problems when Python is installed on a directory with spaces on Windows and the `sys.executable` variable doesn't exactly match `argv[0]`.

Closes #216   At least on my system this was the root of the problem.

2021-06-23 11:47 UTC, webknjaz commented on setuptools/command/install_scripts.py
> +        if os.path.abspath(exec_param) == os.path.abspath(sys.executable):
Could you add a test for this?

2021-06-23 11:49 UTC, webknjaz requested changes
Also, besides the test, this change requires a changelog entry.
Here's how to do this: https://setuptools.readthedocs.io/en/latest/development/developer-guide.html#adding-change-notes-with-your-prs.

2021-06-23 12:38 UTC, set-soft commented
Sorry, but I can't add a test. The error is quite obvious, comparing files by its raw name is a wrong thing to do, no matters the OS.
I work on Linux and I was trying to solve a users problem on Windows.

2021-07-05 01:31 UTC, jaraco commented
After some inspection, I believe this change doesn't achieve the intended goal. Looking at the code, `exec_param` will be `"python.exe"` on Windows. That means that depending on what the current working directory is, `abspath(exec_param)` will be essentially `os.path.join(os.getcwd(), "python.exe")`. For example:

```
>>> os.path.abspath('python.exe') 
'C:\\python.exe' 
```

I'm struggling to imagine a scenario where that's the right thing to compare against `sys.executable`, which is always absolute to begin with.

Coupled with the fact that I was unable to replicate the referenced issue, I suggest to go back to the drawing board. Please at the very least replicate the issue in your environment, make the patch, and then show that the patch corrects the issue. If possible, trace the code at the point before the patch and show what the values are that are implicated in the failure.

Thanks again for the contrib, but I'm declining this one.

2021-07-05 01:31 UTC, closed without merging

2021-07-05 14:48 UTC, set-soft commented
> After some inspection, I believe this change doesn't achieve the intended goal. Looking at the code, `exec_param` will be `"python.exe"` on Windows. That means that depending on what the current working directory is, `abspath(exec_param)` will be essentially `os.path.join(os.getcwd(), "python.exe")`. For example:
> 
> ```
> >>> os.path.abspath('python.exe') 
> 'C:\\python.exe' 
> ```

Not in my case. The value is a full path. And the patch could also be:

```
-        if exec_param == sys.executable:
+       if exec_param == sys.executable or os.path.abspath(exec_param) == os.path.abspath(sys.executable):
```

2021-07-05 14:50 UTC, set-soft commented
> Please at the very least replicate the issue in your environment, make the patch, and then show that the patch corrects the issue. If possible, trace the code at the point before the patch and show what the values are that are implicated in the failure.

The patch was verified to work in my environment! Is not a theoretical patch.

2021-07-05 14:53 UTC, webknjaz commented
Then, a test is needed to prove that it doesn't break envs that aren't yours + it'd be a regression protection. For the maintainers to accept this, there must be at least something they could verify.